### ISSUE TITLE
Le bot ne marche plus

### ISSUE THREAD

**Issue by ney-web** [Greensky-gs/guyguy#3]
Le bot n'envoie jamais d'article

**Comment by Greensky-gs** [comment]
Bonsoir @ney-web , désolé pour ma réponse un peu tardive

Est-ce que tu as un peu plus de détails que ça ? Si ça marchait avant, qu'est-ce que tu as changé sur ton pc, dans le code ou carrément dans Discord, qui pourrait potentiellement causer une erreur ?

Tout semble marcher de mon côté, cependant, j'ai modifié un fichier d'un module, j'ai mis le nouveau fichier en pièces-jointes *- en tant que txt, github le veut pas en js, mais il faut bien le mettre en js*, il faut le mettre dans `node_modules/vinted-api`, au nom de `index.js`

Essaye avec ce nouveau code, et si c'est bien ce qui semble causer l'erreur, j'en ferait un script qui s'activera automatiquement pour le modifier
[index.js.txt](https://github.com/Greensky-gs/guyguy/files/14301894/index.js.txt)

**Comment by ney-web** [comment]
Salut, oui j'ai réglé le problème effectivement ça venait du module "vinted-api", j'ai corrigé le problème de cookie.

J'ai remarqué que l'autre manière de récupérer des articles Vinted, ne marchait plus.

[VintedAPI.ts.txt](https://github.com/Greensky-gs/guyguy/files/14307145/VintedAPI.ts.txt)

**Comment by Greensky-gs** [comment]
Quelle autre manière ?

**Comment by ney-web** [comment]
La partie utilisant le Wrapper
